# Generated by Django 5.1.4 on 2024-12-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('taskCate', '0002_remove_task_cate_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='task_cate',
            field=models.ManyToManyField(to='taskCate.task_cate'),
        ),
    ]
